### ISSUE TITLE
Tracking issue for login page

### ISSUE THREAD

**Issue by NaserParhizkar** [AliParhizkar/CaspianV1#6]
- [x] [Modifying Main project based on InteractiveServer template](https://github.com/AliParhizkar/CaspianV1/issues/8)
- [x] [Update first project dependent projects based on Blazor version 8](https://github.com/AliParhizkar/CaspianV1/issues/9)

**Comment by NaserParhizkar** [comment]
```[tasklist]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```

**Comment by NaserParhizkar** [comment]
- [x] [Design new landing page](https://github.com/octocat/octoproject/issues/4)
- [ ] [Translate content into supported languages](https://github.com/octocat/octoproject/issues/11)
